export enum ConfigTypes {
  DISCORD_TOKEN = "DISCORD_TOKEN",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  TOPGG_TOKEN = "TOPGG_TOKEN",
  LOGO = "LOGO",
  COLOR = "COLOR",
  EXTRA_LOGGING = "EXTRA_LOGGING",
  DEVELOPERS = "DEVELOPERS",
  ACTIVITIES = "ACTIVITIES",
  ACTIVITIES_FREQUENCY_MINUTES = "ACTIVITIES_FREQUENCY_MINUTES",
  REDIS_HOST = "REDIS_HOST",
}
