name: "CI"

on:
  push:
    branches:
      - 'main'
      - 'development' # Added 'development' branch
    paths-ignore:
      - '**.md'
      - '**.toml'
      - 'docker-compose.yml'

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    name: Build and push Docker images.
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest production
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: omznc/slashy:latest
        if: github.ref == 'refs/heads/main' # Only push latest when on the 'main' branch
      -
        name: Build and push with commit hash
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: omznc/slashy:${{ github.sha }} # Use commit hash as the tag
        if: github.ref == 'refs/heads/main' # Only push with commit hash when on the 'main' branch
      -
        name: Build and push development
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: omznc/slashy:development # Push with 'development' tag for the 'development' branch
