name: "CI"

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    name: Build and push Docker images.
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: omznc/slashy:postgresql
      -
        name: Replace MySQL with PostgreSQL
        run: |
          ls -l
          sed -ie 's/postgresql/mysql/g' prisma/schema.prisma
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: omznc/slashy:mysql
