name: Docker - Production

on:
    push:
        branches:
            - 'main'
        paths-ignore:
            - '**.md'
            - '**.toml'
            - 'docker-compose.yml'

jobs:
    build-docker-images:
        runs-on: ubuntu-latest
        name: Build and push Docker images.
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push latest
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    tags: omznc/slashy:latest
                    platforms: linux/amd64,linux/arm64


            -   name: Build and push with commit hash
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    tags: omznc/slashy:${{ github.sha }}
                    platforms: linux/amd64,linux/arm64

